# Generated by Django 3.1.7 on 2021-04-07 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('num_questions', models.IntegerField(default=0)),
                ('num_badges', models.IntegerField(default=0)),
                ('first_question', models.BooleanField(default=False)),
                ('five_questions', models.BooleanField(default=False)),
                ('ten_questions', models.BooleanField(default=False)),
                ('three_day_streak', models.BooleanField(default=False)),
                ('five_day_streak', models.BooleanField(default=False)),
                ('seven_day_streak', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
