# Generated by Django 3.1.7 on 2021-04-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='five_day_streak',
            new_name='four_day_streak',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seven_day_streak',
        ),
        migrations.AddField(
            model_name='profile',
            name='two_day_streak',
            field=models.BooleanField(default=False),
        ),
    ]
