# Generated by Django 3.1.7 on 2021-04-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210415_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='just_gainded_badge',
            field=models.BooleanField(default=False),
        ),
    ]
