# Generated by Django 3.1.7 on 2021-04-08 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
